package pPartida;

import java.util.Random;
import javax.swing.JButton;
import javax.swing.JOptionPane;

public class VistaForm extends javax.swing.JFrame implements IVista{
    
    private int elemJ1;
    private int elemJ2;
    private int elemMaquina;
    String item = "";
    Presentador presenter;
    /**
     * Creates new form VistaForm
     */
    public VistaForm() {
        initComponents();
        this.PanelInicio.setVisible(true);
        this.PanelRival.setVisible(false);
        this.PanelPartida.setVisible(false);
        this.elegirRival();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPartida = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultados = new javax.swing.JTextArea();
        btnPapelJ1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtElementoElegidoJ1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtElementoElegidoRival = new javax.swing.JLabel();
        btnSalirPartida = new javax.swing.JButton();
        btnTijeraJ1 = new javax.swing.JButton();
        btnPiedraJ1 = new javax.swing.JButton();
        btnPiedraRival = new javax.swing.JButton();
        btnPapelRival = new javax.swing.JButton();
        btnTijeraRival = new javax.swing.JButton();
        btnListoRival = new javax.swing.JButton();
        btnListoJ1 = new javax.swing.JButton();
        PanelRival = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        TextoJugador = new javax.swing.JLabel();
        Rival = new javax.swing.JLabel();
        Jugador = new javax.swing.JLabel();
        ElegirRival = new javax.swing.JComboBox<>();
        btnEmpezarJuego = new javax.swing.JButton();
        btnSalirRival = new javax.swing.JButton();
        PanelInicio = new javax.swing.JPanel();
        btnIniciarJuego = new javax.swing.JButton();
        btnRecuperarJuego = new javax.swing.JButton();
        FondoPInicio = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelPartida.setOpaque(false);
        PanelPartida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIENVENIDO AL JAKENPOP");
        PanelPartida.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 720, 50));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel2.setText("Resultados de la Partida:");
        PanelPartida.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 230, 50));

        txtResultados.setColumns(20);
        txtResultados.setRows(5);
        jScrollPane1.setViewportView(txtResultados);

        PanelPartida.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 250, 320));

        btnPapelJ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/papel1.png"))); // NOI18N
        btnPapelJ1.setContentAreaFilled(false);
        btnPapelJ1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/papel1.png"))); // NOI18N
        btnPapelJ1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/papel2.png"))); // NOI18N
        btnPapelJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPapelJ1ActionPerformed(evt);
            }
        });
        PanelPartida.add(btnPapelJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 120, 120));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3.setFocusable(false);
        PanelPartida.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 120, 10, 290));

        jLabel4.setFont(new java.awt.Font("Cooper Black", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("RIVAL");
        PanelPartida.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 80, 270, 50));

        jLabel5.setFont(new java.awt.Font("Cooper Black", 1, 36)); // NOI18N
        jLabel5.setText("JUGADOR 1");
        PanelPartida.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 290, 50));

        txtElementoElegidoJ1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        PanelPartida.add(txtElementoElegidoJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, 100, 30));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel7.setText("ELEMENTO ELEGIDO: ");
        PanelPartida.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 180, 30));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel8.setText("ELEMENTO ELEGIDO: ");
        PanelPartida.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 390, 180, 30));

        txtElementoElegidoRival.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        PanelPartida.add(txtElementoElegidoRival, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 390, 100, 30));

        btnSalirPartida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnCancelar1.png"))); // NOI18N
        btnSalirPartida.setContentAreaFilled(false);
        btnSalirPartida.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnCancelar1.png"))); // NOI18N
        btnSalirPartida.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnCancelar2.png"))); // NOI18N
        btnSalirPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirPartidaActionPerformed(evt);
            }
        });
        PanelPartida.add(btnSalirPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 480, 160, 60));

        btnTijeraJ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tijera1.png"))); // NOI18N
        btnTijeraJ1.setContentAreaFilled(false);
        btnTijeraJ1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tijera1.png"))); // NOI18N
        btnTijeraJ1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tijera2.png"))); // NOI18N
        btnTijeraJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTijeraJ1ActionPerformed(evt);
            }
        });
        PanelPartida.add(btnTijeraJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, 120, 120));

        btnPiedraJ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/piedra1.png"))); // NOI18N
        btnPiedraJ1.setContentAreaFilled(false);
        btnPiedraJ1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/piedra1.png"))); // NOI18N
        btnPiedraJ1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/piedra2.png"))); // NOI18N
        btnPiedraJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPiedraJ1ActionPerformed(evt);
            }
        });
        PanelPartida.add(btnPiedraJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 120, 120));

        btnPiedraRival.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/piedra1.png"))); // NOI18N
        btnPiedraRival.setContentAreaFilled(false);
        btnPiedraRival.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/piedra1.png"))); // NOI18N
        btnPiedraRival.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/piedra2.png"))); // NOI18N
        btnPiedraRival.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPiedraRivalActionPerformed(evt);
            }
        });
        PanelPartida.add(btnPiedraRival, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 130, 120, 120));

        btnPapelRival.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/papel1.png"))); // NOI18N
        btnPapelRival.setContentAreaFilled(false);
        btnPapelRival.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/papel1.png"))); // NOI18N
        btnPapelRival.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/papel2.png"))); // NOI18N
        btnPapelRival.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPapelRivalActionPerformed(evt);
            }
        });
        PanelPartida.add(btnPapelRival, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 260, 120, 120));

        btnTijeraRival.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tijera1.png"))); // NOI18N
        btnTijeraRival.setContentAreaFilled(false);
        btnTijeraRival.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tijera1.png"))); // NOI18N
        btnTijeraRival.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tijera2.png"))); // NOI18N
        btnTijeraRival.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTijeraRivalActionPerformed(evt);
            }
        });
        PanelPartida.add(btnTijeraRival, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 260, 120, 120));

        btnListoRival.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnListo1.png"))); // NOI18N
        btnListoRival.setContentAreaFilled(false);
        btnListoRival.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnListo1.png"))); // NOI18N
        btnListoRival.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnListo2.png"))); // NOI18N
        PanelPartida.add(btnListoRival, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 420, 190, 50));

        btnListoJ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnListo1.png"))); // NOI18N
        btnListoJ1.setContentAreaFilled(false);
        btnListoJ1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnListo1.png"))); // NOI18N
        btnListoJ1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnListo2.png"))); // NOI18N
        PanelPartida.add(btnListoJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 190, 50));

        getContentPane().add(PanelPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, 30, 1180, 540));

        PanelRival.setOpaque(false);
        PanelRival.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("SELECCIÓN DE RIVAL");
        PanelRival.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 490, 30));

        TextoJugador.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        TextoJugador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextoJugador.setText("Usted es el Jugador 1");
        TextoJugador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelRival.add(TextoJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 220, 70));

        Rival.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        Rival.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Rival.setText("Rival:");
        PanelRival.add(Rival, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 200, 60));

        Jugador.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        Jugador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jugador.setText("Jugador:");
        PanelRival.add(Jugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 200, 60));

        ElegirRival.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        ElegirRival.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Eliga su rival" }));
        PanelRival.add(ElegirRival, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 180, 50));

        btnEmpezarJuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnEmpezar1.png"))); // NOI18N
        btnEmpezarJuego.setContentAreaFilled(false);
        btnEmpezarJuego.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnEmpezar1.png"))); // NOI18N
        btnEmpezarJuego.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnEmpezar2.png"))); // NOI18N
        btnEmpezarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpezarJuegoActionPerformed(evt);
            }
        });
        PanelRival.add(btnEmpezarJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 370, 80));

        btnSalirRival.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnCancelar1.png"))); // NOI18N
        btnSalirRival.setContentAreaFilled(false);
        btnSalirRival.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnCancelar1.png"))); // NOI18N
        btnSalirRival.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnCancelar2.png"))); // NOI18N
        btnSalirRival.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirRivalActionPerformed(evt);
            }
        });
        PanelRival.add(btnSalirRival, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, 160, 60));

        getContentPane().add(PanelRival, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 710, 510));

        PanelInicio.setOpaque(false);
        PanelInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIniciarJuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnjugar1.png"))); // NOI18N
        btnIniciarJuego.setContentAreaFilled(false);
        btnIniciarJuego.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnjugar1.png"))); // NOI18N
        btnIniciarJuego.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnjugar2.png"))); // NOI18N
        btnIniciarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarJuegoActionPerformed(evt);
            }
        });
        PanelInicio.add(btnIniciarJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 370, 80));

        btnRecuperarJuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnRecuperar1.png"))); // NOI18N
        btnRecuperarJuego.setContentAreaFilled(false);
        btnRecuperarJuego.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnRecuperar1.png"))); // NOI18N
        btnRecuperarJuego.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnRecuperar2.png"))); // NOI18N
        PanelInicio.add(btnRecuperarJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 370, 80));
        PanelInicio.add(FondoPInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 380));

        getContentPane().add(PanelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 690, 390));

        Fondo.setBackground(new java.awt.Color(51, 204, 255));
        Fondo.setForeground(new java.awt.Color(153, 255, 255));
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo2.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarJuegoActionPerformed
        this.PanelInicio.setVisible(false);
        this.PanelRival.setVisible(true);

    }//GEN-LAST:event_btnIniciarJuegoActionPerformed

    private void btnPiedraJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPiedraJ1ActionPerformed
        this.setElementoJ1(1);
    }//GEN-LAST:event_btnPiedraJ1ActionPerformed

    private void btnPapelJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPapelJ1ActionPerformed
        this.setElementoJ1(2);
    }//GEN-LAST:event_btnPapelJ1ActionPerformed

    private void btnTijeraJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTijeraJ1ActionPerformed
        this.setElementoJ1(3);
    }//GEN-LAST:event_btnTijeraJ1ActionPerformed

    private void btnPiedraRivalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPiedraRivalActionPerformed
        this.setElementoJ2(1);
    }//GEN-LAST:event_btnPiedraRivalActionPerformed

    private void btnPapelRivalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPapelRivalActionPerformed
        this.setElementoJ2(2);
    }//GEN-LAST:event_btnPapelRivalActionPerformed

    private void btnTijeraRivalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTijeraRivalActionPerformed
        this.setElementoJ2(3);
    }//GEN-LAST:event_btnTijeraRivalActionPerformed

    private void btnSalirRivalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirRivalActionPerformed
        this.PanelRival.setVisible(false);
        this.PanelInicio.setVisible(true);
    }//GEN-LAST:event_btnSalirRivalActionPerformed

    private void btnEmpezarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpezarJuegoActionPerformed
        this.PanelRival.setVisible(false);
        this.PanelPartida.setVisible(true);
        this.rivalEleg();
    }//GEN-LAST:event_btnEmpezarJuegoActionPerformed

    private void btnSalirPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirPartidaActionPerformed
        this.PanelPartida.setVisible(false);
        this.PanelInicio.setVisible(true);
        this.txtResultados.setText("");
        this.setItem(" ");
    }//GEN-LAST:event_btnSalirPartidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaForm().setVisible(true);
            }
        });
    }

    @Override
    public void setPresentador(Presentador p) {
        presenter = p;
    }

    @Override
    public void contraJugador() {
        this.PanelPartida.setVisible(true);
    }

    @Override
    public void contraMaquina() {
        this.PanelPartida.setVisible(true);
        this.btnListoRival.setEnabled(false);
        this.btnPiedraRival.setEnabled(false);
        this.btnPapelRival.setEnabled(false);
        this.btnTijeraRival.setEnabled(false);
    }
    
    public void setElementoJ1(int elemento){
        this.elemJ1=elemento;
    }
    
    public void setElementoJ2(int elemento){
        this.elemJ2=elemento;
    }

    @Override
    public int elementoJ1() {
        return elemJ1;
    }

    @Override
    public int elementoJ2() {
        return elemJ2;
    }

    @Override
    public int elementoMaquina() {
        Random r = new Random();
        int valorDado = r.nextInt(3)+1;
        elemMaquina = valorDado;
        return elemMaquina;
    }

    @Override
    public void iniciarJuego() {
        
    }

    @Override
    public void MsjGanadorPartida() {
        
    }

    @Override
    public void MsjGanadorRonda(int elementoJugador, int elementoRival) {
        
    }

    @Override
    public void MostrarResultadosRonda() {
        
    }

    @Override
    public void recuperarJuego() {
        
    }

    @Override
    public void inicio() {
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    @Override
    public void elegirRival() {
        ElegirRival.addItem("j2");
        ElegirRival.addItem("m");
        
    }
    
    public void rivalEleg(){
            item = ElegirRival.getSelectedItem().toString();
            if ("j2".equals(item)) {
            this.contraJugador();
            }else if ("m".equals(item)) {
            this.contraMaquina();
            }
        
    }

    public String getItem() {
        return item;
    }

    public void setItem(String item) {
        this.item = item;
    }
    
    

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ElegirRival;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel FondoPInicio;
    private javax.swing.JLabel Jugador;
    private javax.swing.JPanel PanelInicio;
    private javax.swing.JPanel PanelPartida;
    private javax.swing.JPanel PanelRival;
    private javax.swing.JLabel Rival;
    private javax.swing.JLabel TextoJugador;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnEmpezarJuego;
    private javax.swing.JButton btnIniciarJuego;
    private javax.swing.JButton btnListoJ1;
    private javax.swing.JButton btnListoRival;
    private javax.swing.JButton btnPapelJ1;
    private javax.swing.JButton btnPapelRival;
    private javax.swing.JButton btnPiedraJ1;
    private javax.swing.JButton btnPiedraRival;
    private javax.swing.JButton btnRecuperarJuego;
    private javax.swing.JButton btnSalirPartida;
    private javax.swing.JButton btnSalirRival;
    private javax.swing.JButton btnTijeraJ1;
    private javax.swing.JButton btnTijeraRival;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtElementoElegidoJ1;
    private javax.swing.JLabel txtElementoElegidoRival;
    private javax.swing.JTextArea txtResultados;
    // End of variables declaration//GEN-END:variables
}
